# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains.xdc

# Block Designs: bd/RTC_test/RTC_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RTC_test || ORIG_REF_NAME==RTC_test} -quiet] -quiet

# IP: bd/RTC_test/ip/RTC_test_I2C_RTC_0_0/RTC_test_I2C_RTC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RTC_test_I2C_RTC_0_0 || ORIG_REF_NAME==RTC_test_I2C_RTC_0_0} -quiet] -quiet

# IP: bd/RTC_test/ip/RTC_test_I2Cmod_0_0/RTC_test_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RTC_test_I2Cmod_0_0 || ORIG_REF_NAME==RTC_test_I2Cmod_0_0} -quiet] -quiet

# IP: bd/RTC_test/ip/RTC_test_UART_TXmod_0_0/RTC_test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RTC_test_UART_TXmod_0_0 || ORIG_REF_NAME==RTC_test_UART_TXmod_0_0} -quiet] -quiet

# XDC: c:/Users/rjaco/Documents/Skolgrejs/FPGA_testing/data_length_test/data_length_test.gen/sources_1/bd/RTC_test/RTC_test_ooc.xdc
