# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/reboot_test_block/reboot_test_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==reboot_test_block || ORIG_REF_NAME==reboot_test_block} -quiet] -quiet

# IP: bd/reboot_test_block/ip/reboot_test_block_fpga_rebooter_0_0/reboot_test_block_fpga_rebooter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==reboot_test_block_fpga_rebooter_0_0 || ORIG_REF_NAME==reboot_test_block_fpga_rebooter_0_0} -quiet] -quiet

# IP: bd/reboot_test_block/ip/reboot_test_block_reboot_control_0_0/reboot_test_block_reboot_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==reboot_test_block_reboot_control_0_0 || ORIG_REF_NAME==reboot_test_block_reboot_control_0_0} -quiet] -quiet

# IP: bd/reboot_test_block/ip/reboot_test_block_UART_TXmod_0_0/reboot_test_block_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==reboot_test_block_UART_TXmod_0_0 || ORIG_REF_NAME==reboot_test_block_UART_TXmod_0_0} -quiet] -quiet

# XDC: d:/Code/GLITCH-Software/FPGA/Reboot_test/Reboot_test.gen/sources_1/bd/reboot_test_block/reboot_test_block_ooc.xdc
