# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/Block_Test/Block_Test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test || ORIG_REF_NAME==Block_Test} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_UART_RXmod_0_0/Block_Test_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_UART_RXmod_0_0 || ORIG_REF_NAME==Block_Test_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_UART_TXmod_0_0_1/Block_Test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_UART_TXmod_0_0 || ORIG_REF_NAME==Block_Test_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_Pulsemod_0_0_1/Block_Test_Pulsemod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_Pulsemod_0_0 || ORIG_REF_NAME==Block_Test_Pulsemod_0_0} -quiet] -quiet

# XDC: c:/Users/Sebastian Magnusson/Documents/GitHub/GLITCH-Software/FPGA/UART/UART_Continuation/UART_Continuation.gen/sources_1/bd/Block_Test/Block_Test_ooc.xdc
