# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/rjaco/Documents/Skolgrejs/FPGA_testing/SPI/SPI_Test/SPI_Test.srcs/constrs_1/new/constraints.xdc

# Block Designs: bd/SD_init_test/SD_init_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_init_test || ORIG_REF_NAME==SD_init_test} -quiet] -quiet

# IP: bd/SD_init_test/ip/SD_init_test_UART_TXmod_0_0/SD_init_test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_init_test_UART_TXmod_0_0 || ORIG_REF_NAME==SD_init_test_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/SD_init_test/ip/SD_init_test_SD_init_0_1/SD_init_test_SD_init_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD_init_test_SD_init_0_1 || ORIG_REF_NAME==SD_init_test_SD_init_0_1} -quiet] -quiet

# XDC: c:/Users/rjaco/Documents/Skolgrejs/FPGA_testing/SPI/SD_Test/SD_Test.gen/sources_1/bd/SD_init_test/SD_init_test_ooc.xdc
