# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Code/GLITCH-Software/FPGA/UART/UART_Test/UART_Test.srcs/constrs_1/new/Constraints.xdc

# Block Designs: bd/TM_Block/TM_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TM_Block || ORIG_REF_NAME==TM_Block} -quiet] -quiet

# IP: bd/TM_Block/ip/TM_Block_MUX_2to1_0_0/TM_Block_MUX_2to1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TM_Block_MUX_2to1_0_0 || ORIG_REF_NAME==TM_Block_MUX_2to1_0_0} -quiet] -quiet

# IP: bd/TM_Block/ip/TM_Block_UART_TXmod_0_0/TM_Block_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TM_Block_UART_TXmod_0_0 || ORIG_REF_NAME==TM_Block_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/TM_Block/ip/TM_Block_Switchmod_0_0/TM_Block_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TM_Block_Switchmod_0_0 || ORIG_REF_NAME==TM_Block_Switchmod_0_0} -quiet] -quiet

# IP: bd/TM_Block/ip/TM_Block_util_vector_logic_0_0/TM_Block_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TM_Block_util_vector_logic_0_0 || ORIG_REF_NAME==TM_Block_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/Code/GLITCH-Software/FPGA/Telemetry_test/Telemetry_test.gen/sources_1/bd/TM_Block/TM_Block_ooc.xdc
