# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Code/GLITCH-Software/FPGA/I2C/I2C_Test/I2C_Test.srcs/constrs_1/new/constraints.xdc

# Block Designs: bd/I2C_RTC_test/I2C_RTC_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_RTC_test || ORIG_REF_NAME==I2C_RTC_test} -quiet] -quiet

# IP: bd/I2C_RTC_test/ip/I2C_RTC_test_I2C_RTC_0_0/I2C_RTC_test_I2C_RTC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_RTC_test_I2C_RTC_0_0 || ORIG_REF_NAME==I2C_RTC_test_I2C_RTC_0_0} -quiet] -quiet

# IP: bd/I2C_RTC_test/ip/I2C_RTC_test_UART_TXmod_0_0/I2C_RTC_test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_RTC_test_UART_TXmod_0_0 || ORIG_REF_NAME==I2C_RTC_test_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/I2C_RTC_test/ip/I2C_RTC_test_I2Cmod_0_0/I2C_RTC_test_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_RTC_test_I2Cmod_0_0 || ORIG_REF_NAME==I2C_RTC_test_I2Cmod_0_0} -quiet] -quiet

# XDC: d:/Code/FPGA_testing/TC_TM_tests/TC_TM_tests.gen/sources_1/bd/I2C_RTC_test/I2C_RTC_test_ooc.xdc
