# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Code/GLITCH-Software/FPGA/UART/UART_Continuation/UART_Continuation.srcs/constrs_1/new/Constraints.xdc

# Block Designs: bd/GNSS_Reader/GNSS_Reader.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GNSS_Reader || ORIG_REF_NAME==GNSS_Reader} -quiet] -quiet

# IP: bd/GNSS_Reader/ip/GNSS_Reader_UART_TXmod_0_0/GNSS_Reader_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GNSS_Reader_UART_TXmod_0_0 || ORIG_REF_NAME==GNSS_Reader_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/GNSS_Reader/ip/GNSS_Reader_UART_RXmod_0_0/GNSS_Reader_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GNSS_Reader_UART_RXmod_0_0 || ORIG_REF_NAME==GNSS_Reader_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/GNSS_Reader/ip/GNSS_Reader_UART_TXmod_1_0/GNSS_Reader_UART_TXmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GNSS_Reader_UART_TXmod_1_0 || ORIG_REF_NAME==GNSS_Reader_UART_TXmod_1_0} -quiet] -quiet

# IP: bd/GNSS_Reader/ip/GNSS_Reader_Switchmod_0_0/GNSS_Reader_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GNSS_Reader_Switchmod_0_0 || ORIG_REF_NAME==GNSS_Reader_Switchmod_0_0} -quiet] -quiet

# XDC: d:/Code/GLITCH-Software/FPGA/UART/Read_GNSS/Read_GNSS.gen/sources_1/bd/GNSS_Reader/GNSS_Reader_ooc.xdc
