# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/I2C_Test/I2C_Test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Test || ORIG_REF_NAME==I2C_Test} -quiet] -quiet

# IP: bd/I2C_Test/ip/I2C_Test_I2Cmod_0_0/I2C_Test_I2Cmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Test_I2Cmod_0_0 || ORIG_REF_NAME==I2C_Test_I2Cmod_0_0} -quiet] -quiet

# IP: bd/I2C_Test/ip/I2C_Test_UART_TXmod_0_0/I2C_Test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Test_UART_TXmod_0_0 || ORIG_REF_NAME==I2C_Test_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/I2C_Test/ip/I2C_Test_Read_Sensorsmod_0_0/I2C_Test_Read_Sensorsmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Test_Read_Sensorsmod_0_0 || ORIG_REF_NAME==I2C_Test_Read_Sensorsmod_0_0} -quiet] -quiet

# IP: bd/I2C_Test/ip/I2C_Test_Switchmod_0_0/I2C_Test_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I2C_Test_Switchmod_0_0 || ORIG_REF_NAME==I2C_Test_Switchmod_0_0} -quiet] -quiet

# XDC: d:/Code/GLITCH-Software/FPGA/I2C/I2C_Test/I2C_Test.gen/sources_1/bd/I2C_Test/I2C_Test_ooc.xdc
