# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Code/GLITCH-Software/FPGA/UART/UART_Test/UART_Test.srcs/constrs_1/new/Constraints.xdc

# Block Designs: bd/Block_Test/Block_Test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test || ORIG_REF_NAME==Block_Test} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_UART_RXmod_0_0/Block_Test_UART_RXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_UART_RXmod_0_0 || ORIG_REF_NAME==Block_Test_UART_RXmod_0_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_UART_TXmod_0_0/Block_Test_UART_TXmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_UART_TXmod_0_0 || ORIG_REF_NAME==Block_Test_UART_TXmod_0_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_Switchmod_0_0/Block_Test_Switchmod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_Switchmod_0_0 || ORIG_REF_NAME==Block_Test_Switchmod_0_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_UART_TXmod_1_0/Block_Test_UART_TXmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_UART_TXmod_1_0 || ORIG_REF_NAME==Block_Test_UART_TXmod_1_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_UART_RXmod_1_0/Block_Test_UART_RXmod_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_UART_RXmod_1_0 || ORIG_REF_NAME==Block_Test_UART_RXmod_1_0} -quiet] -quiet

# IP: bd/Block_Test/ip/Block_Test_MUX_2to1_0_4/Block_Test_MUX_2to1_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Test_MUX_2to1_0_4 || ORIG_REF_NAME==Block_Test_MUX_2to1_0_4} -quiet] -quiet

# XDC: d:/Code/GLITCH-Software/FPGA/UART/GNSS_and_UART/GNSS_and_UART.gen/sources_1/bd/Block_Test/Block_Test_ooc.xdc
